services:
  - type: web
    name: tu-app-laravel
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan optimize:clear
      php artisan optimize
    startCommand: |
      php artisan serve --host=0.0.0.0 --port=8000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        fromSecret: APP_KEY