services:
  - type: web
    name: laravel-portfolio
    env: php
    plan: free
    buildCommand: "chmod -R 755 storage bootstrap/cache && composer install --no-dev --optimize-autoloader"
    startCommand: "php -S 0.0.0.0:8000 -t public"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
